spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/realty
    username: ${PGLOGIN}
    password: ${PGPASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      read-unknown-enum-values-as-null: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${FLATSMAILLOGIN}
    password: ${FLATSMAILPASSWORD}
    app-password: ${FLATSMAILAPPPASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8080
  servlet:
    context-path: "/realty/api"

custom:
  jwt:
    secret: QAZ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYz
    issuer: by.potapchuk
  feign:
    audit-logs:
      url: http://localhost:8081/realty/api
  email:
    messages:
      verification: |
        follow the link below to complete the verification process in the application search-realty 
        http://localhost:8080/realty/api/users/verification?email=%s&token=%s
      updatePassword: |
        follow the link bellow to change your password in the application search-realty
        If you do not want change the password in the application, then ignore this letter.  
        http://localhost:8080/realty/forgot-password?token=%s