spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/realty

custom:
  feign:
    audit-logs:
      url: http://localhost:8081/realty/api
  email:
    messages:
      verification: |
        follow the link below to complete the verification process in the application search-realty 
        http://localhost:8080/realty/api/users/verification?email=%s&token=%s
      updatePassword: |
        follow the link bellow to change your password in the application search-realty
        If you do not want change the password in the application, then ignore this letter.  
        http://localhost:8080/realty/forgot-password?token=%s

server:
  port: 8080