spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/audit
    username: ${PGLOGIN}
    password: ${PGPASSWORD}
    hikari:
      maximum-pool-size: 10
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    deserialization:
      read-unknown-enum-values-as-null: true
server:
  port: 8081
  servlet:
    context-path: "/realty/api"

app:
  beans:
    file-generators:
      xml:
        enabled: false
  jwt:
    secret: QAZ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYz
    issuer: by.potapchuk

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus, metrics, info, env, liquibase
  endpoint:
    health:
      probes:
        enabled: true