openapi: 3.0.0
info:
  version: 1.0.0
  title: Поиск жилья

servers:
  - url: http://{host}:{port}
    description: custom server
    variables:
      host:
        description: host name
        default: localhost
      port:
        description: port value
        default: "80"

tags:
  - name: "Поиск"
    description: "Поиск недвижимости"
  - name: "Закладки"
    description: "Раздел личного кабинета пользователя с избранной недвижимостью"
  - name: "Подписки"
    description: "Раздел личного кабинета пользователя с подписками на уведомления о новом жилье по параметрам"
paths:
  /api/v1/flats:
    get:
      tags:
        - "Поиск"
      summary: "Получить страницу с недвижимостью"
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Номер страницы
          required: false
        - in: query
          name: size
          schema:
            type: integer
            minimum: 1
            default: 20
          description: Размер страницы
          required: false
        - in: query
          name: price[from]
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Цена недвижимости от
          required: false
        - in: query
          name: price[to]
          schema:
            type: integer
            minimum: 1
          description: Цена недвижимости до
          required: false
        - in: query
          name: bedrooms[from]
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Количество комнат от
          required: false
        - in: query
          name: bedrooms[to]
          schema:
            type: integer
            minimum: 1
          description: Количество комнат до
          required: false
        - in: query
          name: area[from]
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Площадь от
          required: false
        - in: query
          name: area[to]
          schema:
            type: integer
            minimum: 1
          description: Площадь до
          required: false
        - in: query
          name: floors[]
          schema:
            type: array
            items:
              type: integer
          description: Номер этажа
          required: false
        - in: query
          name: photo
          schema:
            type: boolean
          description: Обязательно с фото
          required: false
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfFlat'
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
  /api/v1/flats/{uuid}/bookmark:
    get:
      tags:
        - "Закладки"
      summary: "Добавить недвижимость в собственные закладки"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          description: "Идентификатор объявления"
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
    delete:
      tags:
        - "Закладки"
      summary: "Удалить недвижимость из собственных закладок"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          description: "Идентификатор объявления"
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
  /api/v1/bookmark:
    get:
      tags:
        - "Закладки"
      summary: "Просмотр недвижимости в закладках"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfSubscribe'
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
  /api/v1/subscribe:
    post:
      tags:
        - "Подписки"
      summary: "Создать подписку на уведомления"
      security:
        - bearerAuth: []
      requestBody:
        $ref: "#/components/requestBodies/CreateSubscribe"
      responses:
        '201':
          description: "Подписка добавлена"
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
    get:
      tags:
        - "Подписки"
      summary: "Просмотр подписок"
      security:
        - bearerAuth: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfFlat'
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
  /api/v1/subscribe/{uuid}/dt_update/{dt_update}:
    put:
      tags:
        - "Подписки"
      summary: "Изменить подписку"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          description: "Идентификатор подписки"
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: dt_update
          required: true
          schema:
            type: integer
            format: int64
          description: "Дата последнего обновления записи"
      requestBody:
        $ref: "#/components/requestBodies/CreateSubscribe"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfFlat'
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
    delete:
      tags:
        - "Подписки"
      summary: "Удалить подписку"
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: uuid
          description: "Идентификатор подписки"
          required: true
          schema:
            type: string
            format: uuid
        - in: path
          name: dt_update
          required: true
          schema:
            type: integer
            format: int64
          description: "Дата последнего обновления записи"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageOfFlat'
        '400':
          $ref: '#/components/responses/Bad_Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '500':
          $ref: '#/components/responses/Internal_Server_Error'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  requestBodies:
    CreateSubscribe:
      description: Тело для создания Подписки
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Subscribe'
  responses:
    Bad_Request:
      description: Запрос некорректен. Сервер не может обработать запрос
      content:
        application/json:
          schema:
            oneOf:
              - type: array
                items:
                  $ref: '#/components/schemas/t_error_response'
              - $ref: '#/components/schemas/t_structured_error_response'
          examples:
            t_error_response:
              value:
                - logref: error
                  message:  Запрос содержит некорректные данные. Измените запрос и отправьте его ещё раз
            t_structured_error_response:
              value:
                logref: structured_error
                errors:
                  - field: time_unit
                    message: Поле должно быть положительным числом
    Unauthorized:
      description: Для выполнения запроса на данный адрес требуется передать токен авторизации
    Forbidden:
      description: Данному токенту авторизации запрещено выполнять запроса на данный адрес
    Internal_Server_Error:
      description: Внутренняя ошибка сервера. Сервер не смог корректно обработать запрос
      content:
        applicaion/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/t_error_response'
          example:
            - logref: error
              message:  Сервер не смог корректно обработать запрос. Пожалуйста обратитесь к администратору
  schemas:
    Flat:
      type: object
      description: Недвижимость
      required:
        - description
        - offer_type
      allOf:
        - $ref: '#/components/schemas/t_base_essence'
      properties:
        offer_type:
          $ref: '#/components/schemas/OfferType'
        description:
          type: string
          description: "Описание"
          example: "Сдаются в аренду уютные офисы с выходом на террасы от 200 до 1950 кв.м"
        area:
          type: integer
          description: "Площадь"
          example: 250
        price:
          type: integer
          description: "Стоимость"
          example: 4000
        floor:
          type: integer
          description: "Этаж"
          example: 3
        bedrooms:
          type: integer
          description: "Количество комнат"
          example: 6
        photo_urls:
          description: "Ссылки на фото объекта"
          type: array
          items:
            type: string
        original_url:
          description: "Ссылка на объявление"
          type: string

    OfferType:
      type: string
      description: |
        Тип предложения:
          * `RENT` - Под аренду
          * `SALE` - Под продажу
      enum:
        - RENT
        - SALE

    PageOfFlat:
      type: object
      description: Страница недвижимости
      allOf:
        - $ref: '#/components/schemas/t_page'
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Flat'

    Subscribe:
      type: object
      description: Подписка
      allOf:
        - $ref: '#/components/schemas/t_base_essence'
      properties:
        params:
          type: object
          properties:
            offer_type:
              $ref: '#/components/schemas/OfferType'
            price:
              description: Цена недвижимости
              $ref: '#/components/schemas/IntInterval'
            bedrooms:
              description: Количество комнат
              $ref: '#/components/schemas/IntInterval'
            area:
              description: Площадь
              $ref: '#/components/schemas/IntInterval'
            floors:
              description: Номер этажа
              type: array
              items:
                type: integer
            photo:
              description: Наличие фото
              type: boolean

    IntInterval:
      type: object
      description: Интервал
      properties:
        from:
          description: от
          type: integer
          minimum: 0
          default: 0
        to:
          description: до
          type: integer
          minimum: 1

    PageOfSubscribe:
      type: object
      description: Страница подписок
      allOf:
        - $ref: '#/components/schemas/t_page'
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/Subscribe'

    t_base_essence:
      type: object
      description: Описание базовой сущности.
      required:
        - uuid
        - dt_create
        - dt_update
      properties:
        uuid:
          description: Уникальный идентификатор сущности
          type: string
          format: uuid
          readOnly: true
        dt_create:
          description: Дата создания сущности (linux time)
          type: number
          format: int64
          readOnly: true
        dt_update:
          description: Дата последнего обновления сущности (linux time)
          type: integer
          format: int64
          readOnly: true

    t_page:
      type: object
      required:
        - number
        - size
        - total_pages
        - total_elements
        - content
        - first
        - number_of_elements
        - last
      description: Страница
      properties:
        number:
          description: Номер текущей запрошенной страницы
          type: integer
          format: int32
        size:
          description: Запрошенное количество элементов на страницу
          type: integer
          format: int32
        total_pages:
          description: Всего количество страниц учитывающих запрашиваемое количество элементов на страницу
          type: integer
          format: int32
        total_elements:
          description: Всего количество записей соответствующих запросу
          type: integer
          format: int64
        first:
          description: Признак является ли страница первой
          type: boolean
        number_of_elements:
          description: Количество элементов на текущей странице
          type: integer
          format: int32
        last:
          description: Признак является ли страница последней
          type: boolean

    t_error_response:
      type: object
      description: Ошибка. Содержит общее описание ошибки
      required:
        - logref
        - message
      properties:
        logref:
          type: string
          description: |
            Тип ошибки (предназначено для машинной обработки):
              * `error` - Признак что ошибка не привязана к полю
          enum:
            - "error"
        message:
          description: Сообщение об ошибке
          type: string
          example: Запрос содержит некорректные данные. Измените запрос и отправьте его ещё раз

    t_structured_error_response:
      type: object
      description: Ошибка. Содержит описание ошибок с отсылками на поля сущности
      required:
        - logref
        - errors
      properties:
        logref:
          type: string
          description: |
            Тип ошибки (предназначено для машинной обработки):
              * `structured_error` - Признак что ошибка привязана к полю
          enum:
            - "structured_error"
        errors:
          description: Список ошибок
          type: array
          items:
            type: object
            properties:
              message:
                type: string
                description: Сообщение об ошибке
                example: Должно быть положительным числом
              field:
                type: string
                description: Наименование поля с которым связано сообщение
                example: time_unit